# Dependencies
# - markdown:         redcarpet
highlighter:      rouge

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Rhymes With Diploma"
tagline: ""
description: "Follow <a href=\"https://micro.blog/tjluoma\">@tjluoma on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/tjluoma\">@tjluoma on Micro.blog</a>."
baseurl: ""
url: "https://www.rhymeswithdiploma.com"
markdown: "kramdown"
username: "tjluoma"
microblog_user: "tjluoma"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Rhymes With Diploma"
name: "Rhymes With Diploma"
gravatar_hash: "4a6830e6e6f7f0795bc3b487b7df19c0"
avatar: "https://micro.blog/tjluoma/avatar.jpg"
full_name: "Rhymes With Diploma"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "6816"
gems: ["jekyll-paginate"]
itunes_description: "Presbyterian pastor (PCUSA) and Mac/iOS Nerd."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "TJ Luoma"
itunes_email: ""
podcast: false